### ISSUE TITLE
Disable comment in failure output

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec#112]
### Subject of the issue

I would love it if we could disable the comment in the output when a test fails:

```diff
- rspec ./spec/domains/campaigns/metric_counts_calculator/call_spec.rb:180 # Campaigns::MetricCountsCalculator#call returns denied count per month and total over months
+ rspec ./spec/domains/campaigns/metric_counts_calculator/call_spec.rb:180
```

### Your environment
* Ruby version: 3.3.6
* rspec-core version: 3.13.2
* rspec-expectations version: 3.13.2
* rspec-mocks version: 3.13.2
* rspec-support version: 3.13.2

### Steps to reproduce

Run a test that fails.

### Expected behavior

We can disable the comment from the output. It's great that there's a command we can quickly copy/paste to run the failing test. I like being able to triple-click and copy the line. However, frequently after running the specific test, I end up wanting to follow up by deleting the line number and running the entire test file. But this is more awkward, since I either need to backspace past the whole comment or somehow navigate to the line number. I'd love to be able to hit up to the previous command and quickly remove/change the line number, without the comment slowing things down.

### Actual behavior

It looks to me like the comment is hard coded, unless I'm missing a setting somewhere.

**Comment by JonRowe** [comment]
:wave: The configurable element here is the formatter, you can implement your own formatter based off ours to remove this if you don't want this.
