### ISSUE TITLE
JSON formatter with shared examples doesn't report line number correctly

### ISSUE THREAD

**Issue by elken** [rspec/rspec#113]
### Subject of the issue

Identified as part of https://github.com/olimorris/neotest-rspec/issues/74#issuecomment-2506786963, it seems that with shared_examples the `line_number` is not correctly reported.

After running this test

```ruby
RSpec.shared_examples 'to be included' do
  it 'adds two numbers together' do
    expect(subject).to eq(1)
  end
end

RSpec.describe 'Failing Group' do
  subject { 2 }
  it_behaves_like 'to be included'
end

RSpec.describe 'Passing Group' do
  subject { 1 }
  it_behaves_like 'to be included'
end
```

We get this back

```json
{
  "version": "3.13.0",
  "examples": [
    {
      "id": "./test.rb[1:1:1]",
      "description": "adds two numbers together",
      "full_description": "Failing Group behaves like to be included adds two numbers together",
      "status": "failed",
      "file_path": "./test.rb",
      "line_number": 2,
      "run_time": 0.005350789,
      "pending_message": null,
      "exception": {
        "class": "RSpec::Expectations::ExpectationNotMetError",
        "message": "\nexpected: 1\n     got: 2\n\n(compared using ==)\n",
        "backtrace": [
          "./test.rb:3:in `block (2 levels) in <top (required)>'"
        ]
      }
    },
    {
      "id": "./test.rb[2:1:1]",
      "description": "adds two numbers together",
      "full_description": "Passing Group behaves like to be included adds two numbers together",
      "status": "passed",
      "file_path": "./test.rb",
      "line_number": 2,
      "run_time": 0.00003978,
      "pending_message": null
    }
  ],
  "summary": {
    "duration": 0.00588696,
    "example_count": 2,
    "failure_count": 1,
    "pending_count": 0,
    "errors_outside_of_examples_count": 0
  },
  "summary_line": "2 examples, 1 failure"
}
```

And as you can see, the line number in both cases is 2; even though in both cases that's wrong.

### Your environment
* Ruby version: 3.3.6
* rspec-core version: 3.13.0
* rspec-expectations version: 3.13.1
* rspec-mocks version: 3.13.1
* rspec-support version: 3.13.1

### Steps to reproduce

1. Create the above test
2. Run with `rspec test.rb -f json` (optionally pipe to `jq` for nicer output)
3. Observe the line numbers being incorrect

### Expected behavior
The line number of the test should show the test case not the example

### Actual behavior
The line number reports from the example rather than the test

**Comment by JonRowe** [comment]
:wave: I'm afraid that line number is actually correct, its the line number where the example is declared, this is why the command line orientated formatters show id's for these examples, as the line number is ambiguous
