### ISSUE TITLE
Is allow the best name?

### ISSUE THREAD

**Issue by maedi** [rspec/rspec#66]
I found `allow` hard to understand at first. Could an alias be `alter`?

**Comment by pirj** [comment]
Sure:
```ruby
module Alter
  alias_method :alter, :allow
end

RSpec.configure do |c|
  c.include Alter
end
```

We keep GitHub issues for bugs and feature requests.
Please consider using our mailing list (https://rspec.info/help/) and resources like StackOverflow.
Thanks for understanding.

You shouldn't think of `allow` as altering. It does that underneath, but for the person reading the specs (yes, it is "specs", not "tests"), `allow(user).to receive(:name).and_return('Bob')` should sound exactly as it reads. With "alter" it doesn't read right.
